### ISSUE TITLE
Preparar infraestructura para evento

### ISSUE THREAD

**Issue by rolivencia** [ResetShop/ticketera#39]
# Tareas
- [x] Crear schema y migración en Drizzle para agregar soporte de la tabla `event` en la aplicación.
- [x] Agregar `event` a modelo de dominio
- [x] Crear evento de Gualicho 1.0 en migrations (usar comando `drizzle-kit generate:pg --custom`)
- [x] Enlazar tickets al evento Gualicho 1.0
- [ ] Agregar obtención de `event` en queries relacionadas a `ticket`
- [ ] Chequear cambios necesarios en infraestructura para soportar eventos
- [ ] Reconciliar diagrama con posibles cambios en la definición final del schema (ver casos de `photo` vs `imageUrl` y `alt_organizer` )

## Definiciones pendientes
- ¿Cómo soportamos el evento #2? ¿Seteamos una variable de entorno que apunte al evento de id siguiente para crear todos los tickets con ese ID? (me parece al momento la idea más viable)
- Necesitamos algunos cambios en infraestructura, a definir, para poder crear tickets y obtenerlos con el dato de `event` adjunto.

**Comment by juanblas09** [comment]
Dejo propuesta de diagrama con con "evento" incluida.
A saber:
* `alt_organizer` lleva ese nombre con el proposito de que cuando en un futuro tengamos la clase "organizador" quede como un atributo para ocultar el nombre del organizador real si asi fuese necesario
* `people_limit` puede implementarse ahora o dejarse para una próxima version
* en el gran diagrama original, el `ticket` no se conecta directamente con el `event`
![Diagrama sin título](https://github.com/ResetShop/ticketera/assets/20421887/f1f78f4a-5d8e-4d74-8f83-f42f268ec318)

**Comment by rolivencia** [comment]
Actualizada la descripción @juanblas09
